import { readFileSync } from 'node:fs';

const adminHtml = readFileSync('admin.html', 'utf8');
const judgeHtml = readFileSync('judge.html', 'utf8');
const adminMain = readFileSync('admin-main.js', 'utf8');
const scoreUtils = readFileSync('score-utils.js', 'utf8');
const judgeJs = readFileSync('judge.js', 'utf8');
const resultsHtml = readFileSync('results.html', 'utf8');
const indexHtml = readFileSync('index.html', 'utf8');
const teamHtml = readFileSync('team.html', 'utf8');
const tvHtml = readFileSync('tv.html', 'utf8');
const tvControlHtml = readFileSync('tv-control.html', 'utf8');
const publishHtml = readFileSync('publish.html', 'utf8');
const loginHtml = readFileSync('login.html', 'utf8');
const loginJs = readFileSync('login.js', 'utf8');
const firestoreRules = readFileSync('firestore.rules', 'utf8');
const dependencyLoader = readFileSync('dependency-loader.js', 'utf8');
const festConfig = readFileSync('fest-config.js', 'utf8');
const registerHtml = readFileSync('register.html', 'utf8');
const resetFunction = readFileSync('functions/index.js', 'utf8');
const storageRules = readFileSync('storage.rules', 'utf8');
const brandingConfig = readFileSync('branding-config.js', 'utf8');
const imageUpload = readFileSync('image-upload.js', 'utf8');
const eventUtils = readFileSync('event-utils.js', 'utf8');

const checks = {
  'admin operational readiness': adminHtml.includes('admin-readiness') && adminMain.includes('renderAdminReadiness') && adminMain.includes('Events without judges'),
  'events expose edit and delete only': !adminMain.includes('advance-event-status') && !adminMain.includes('advanceEventStatus') && !adminMain.includes('Next Status') && adminMain.includes('data-admin-action="edit-event"') && adminMain.includes('data-admin-action="delete-event"'),
  'verified schedule persistence': adminMain.includes('SCHEDULE_MASTER_VERIFY_FAILED') && adminMain.includes("scheduleStatus:scheduled?'scheduled':'unscheduled'") && adminMain.includes('[...selectedScheduleRows]') && adminMain.includes('Schedule rows were not saved'),
  'published result queries': indexHtml.includes('where("status", "==", "published")') && resultsHtml.includes('where("status", "==", "published")') && teamHtml.includes('where("status", "==", "published")') && tvHtml.includes("where('status', '==', 'published')"),
  'team scoped notifications': teamHtml.includes('where("team", "in", ["All", currentTeam])') && firestoreRules.includes("resource.data.team in ['All', get(accessDoc()).data.team]"),
  'admin load module': adminHtml.includes('src="./admin-main.js'),
  'admin branded logo loader': adminHtml.includes('id="admin-loader-logo"') && adminHtml.includes('id="admin-loader-fest-name"') && adminMain.includes('applyAdminLoaderBranding') && adminMain.includes("settings', 'home_config") && !readFileSync('admin-auth.js', 'utf8').includes("byId('app-loader')?.classList.add('hide')"),
  'core tab switch actions': ['dashboard', 'downloads', 'registrations', 'students', 'events', 'schedule', 'schedule-review', 'config', 'access', 'public-content', 'poster-certificate', 'tv-display', 'danger', 'guide'].every(tab => adminHtml.includes(`data-tab="${tab}"`)) && !adminHtml.includes('id="nav-scoring"'),
  'master capability setup': adminHtml.includes('data-tab="master-setup"') && adminHtml.includes('id="master-schedule"') && adminHtml.includes('id="master-judging"') && adminHtml.includes('id="master-results"') && adminHtml.includes('id="master-preset-guide"') && adminHtml.includes('id="master-impact-review"') && adminHtml.includes('id="master-scoring-slot"') && adminMain.includes('saveMasterSetup') && adminMain.includes('applyFestCapabilities') && adminMain.includes('renderPresetGuide') && adminMain.includes('renderMasterImpactReview') && adminMain.includes('mergeScoringIntoMasterSetup') && festConfig.includes('FEST_PRESETS') && festConfig.includes('FEST_PRESET_GUIDES'),
  'nested master setup navigation': adminHtml.includes('id="master-setup-subnav"') && ['overview','people-registration','public-view','events-schedule','judging-scoring','review-activate'].every(section=>adminHtml.includes(`data-section="${section}"`)) && ['compass','users-round','panels-top-left','calendar-range','scale','shield-check'].every(icon=>adminHtml.includes(`data-lucide="${icon}"`)) && !adminHtml.includes('id="master-setup-section-header"') && ['page-context','page-status','master-header-actions'].every(id=>adminHtml.includes(`id="${id}"`)) && adminMain.includes('switchMasterSection') && adminMain.includes('setMasterSubnavExpanded') && adminMain.includes("activeMasterSection!=='review-activate'") && adminMain.includes('adminMasterSection'),
  'explicit competition policy centre': ['competition-policy-status','policy-group-position-summary','policy-direct-grade','policy-min-position','policy-joint-position','policy-multi-judge','policy-trim-judges','policy-general-gender','policy-result-correction'].every(id=>adminHtml.includes(`id="${id}"`)) && festConfig.includes('normalizeCompetitionPolicies') && festConfig.includes('incompleteCompetitionPolicies') && adminMain.includes('competitionPoliciesFromForm') && adminMain.includes('Complete Competition Policy Centre') && adminMain.includes("settings','scoring_rules") && judgeJs.includes('Judgement is locked until Admin completes Competition Policy Centre'),
  'master preset guidance and custom participant management': adminHtml.includes('id="master-participant-types"') && !adminHtml.includes('id="master-info-panel"') && adminMain.includes("pop.id='master-help-popover'") && adminHtml.includes('add-participant-type') && adminMain.includes('applyMasterPreset') && adminMain.includes("preset:'custom'") && adminMain.includes('showMasterInfo') && adminMain.includes('masterInfoOpen') && adminMain.includes('participantTypeUsage') && adminMain.includes('[data-master-event-feature]') && ['excelImport','customCriteria','objectiveScoring','timeResults','countResults','directRank','multipleJudges','eventOverrides','workflowStatuses','importHistory','teamLedger'].every(key=>adminMain.includes(`${key}:{title:`)) && adminHtml.includes('.master-info-trigger') && festConfig.includes('FEST_PRESET_GUIDES') && festConfig.includes('normalizeParticipantTypeDefinitions') && !festConfig.includes("'guest', 'public'") && adminMain.includes("action:'master_setup_updated'"),
  'master complexity profiles and overlay help': ['basic','standard','advanced'].every(profile=>adminHtml.includes(`data-profile="${profile}"`)) && adminHtml.includes('id="master-event-field-rules"') && adminMain.includes("'apply-event-profile': () => window.applyEventProfile(d.profile)") && adminMain.includes('eventFieldRulesForMode, readableTextColor') && adminMain.includes('eventFieldRulesFromDom') && festConfig.includes('eventFieldRulesForMode') && eventUtils.includes("rule.requirement==='conditional'"),
  'dynamic scoring awards': !adminHtml.includes('id="automatic-grade-thresholds"') && adminHtml.includes('id="policy-grade-maximum"') && adminHtml.includes('id="policy-group-position-summary"') && adminMain.includes('data-grade-minimum') && adminMain.includes('data-grade-mark') && adminMain.includes('grade labels must be unique') && adminMain.includes('position labels must be unique') && scoreUtils.includes('minimumPercentage:grade.minimumPercentage') && publishHtml.includes('minimumPercentage:configured?.minimumPercentage'),
  'single class source and grade preview': !adminHtml.includes('id="master-eligible-classes"') && adminMain.includes('[data-student-field-options="class"]') && adminMain.includes('updateGradeCalculatedMarks') && adminHtml.includes('Percentage of maximum mark'),
  'configurable student fields and reviewed Excel import': ['student-field-settings','new-student-field-label','student-custom-fields','student-import-modal','student-import-summary','student-import-body'].every(id=>adminHtml.includes(`id="${id}"`)) && adminHtml.includes('Download Model') && adminMain.includes('downloadStudentTemplate') && adminMain.includes('validateImportRow') && adminMain.includes('confirmStudentImport') && adminMain.includes('data-import-target') && adminMain.includes('importCellControl') && adminMain.includes('header:1') && adminMain.includes('assignedChestNo') && adminMain.includes('openStudentTemplate') && adminMain.includes('Examples - Do Not Import') && adminMain.includes('Valid Values') && adminMain.includes('studentDisplayName') && adminMain.includes("action:'student_excel_import'") && festConfig.includes('normalizeStudentFields') && festConfig.includes("key: 'guardianName'") && festConfig.includes("key: 'phone'"),
  'desktop student editor and import toolbars': adminHtml.includes('max-h-[calc(100dvh-1.5rem)]') && adminHtml.includes('id="edit-student-form" class="min-h-0 space-y-4 overflow-y-auto') && ['file-down','file-up','list-plus','sheet'].every(icon=>adminHtml.includes(`data-lucide="${icon}"`)) && ['btn-bulk','btn-event-bulk'].every(id=>adminHtml.includes(`id="${id}" type="button" role="switch" aria-checked="false"`)) && adminHtml.includes('data-bulk-track') && adminHtml.includes('data-bulk-knob') && adminMain.includes('setBulkToggleState') && !adminMain.includes("b.innerText='Switch to Single Mode'") && !adminMain.includes('b.innerText="Switch to Single"'),
  'team setup colors': adminHtml.includes('>Team Setup</span>') && adminMain.includes('saveTeamColor') && adminMain.includes('teamColors') && resultsHtml.includes('assignedTeamColor') && resultsHtml.includes('readableTextColor'),
  'module visibility': indexHtml.includes('applyFestCapabilities') && teamHtml.includes('applyFestCapabilities') && judgeJs.includes('Judgement is disabled'),
  'neutral shared branding': brandingConfig.includes("festName1: 'Fest Management'") && brandingConfig.includes("festName2: 'Setup Required'") && [adminMain,judgeJs,loginJs,indexHtml,resultsHtml,teamHtml,publishHtml,tvHtml,registerHtml].every(source=>source.includes('branding-config.js')),
  'legacy branding removed': ![adminMain,judgeJs,indexHtml,resultsHtml,teamHtml,publishHtml,tvHtml,registerHtml].some(source=>/Sadaye|Madeena|Thirunoor|Fest Adding|2k25/i.test(source)),
  'base64 logo on every branded surface': brandingConfig.includes('applyBase64Image') && [indexHtml,resultsHtml,teamHtml,publishHtml,tvHtml,judgeJs].every(source=>source.includes('applyBase64Image')) && loginJs.includes('applyLogo') && registerHtml.includes('applyLogo') && adminMain.includes('applyLogo') && tvHtml.includes('id="tv-fest-logo"'),
  'public branding does not wait for auth': indexHtml.includes('startPublicData().catch') && resultsHtml.includes('startResultsData().catch') && !indexHtml.includes('onAuthStateChanged(auth') && !resultsHtml.includes('onAuthStateChanged(auth') && indexHtml.includes('public Firestore reads continue') && resultsHtml.includes('public Firestore reads continue'),
  'base64 CSP on every branded page': ['admin.html','index.html','judge.html','login.html','publish.html','results.html','team.html','tv.html'].every(name => readFileSync(name, 'utf8').includes("img-src 'self' https: data: blob:")),
  'powered-by footer retained': [indexHtml,resultsHtml,teamHtml,publishHtml].every(source=>source.includes('Powered by hadi mahiri faizy')&&source.includes('https://www.instagram.com/muhammed_sanjide_p')&&source.includes('rel="noopener noreferrer"')),
  'branding cache invalidation': brandingConfig.includes('clearBrandingCache') && [loginJs,indexHtml,resultsHtml,teamHtml,publishHtml].every(source=>source.includes('clearBrandingCache')) && adminMain.includes('clearBrandingCache'),
  'fresh setup guidance': adminHtml.includes('id="admin-setup-required"') && adminHtml.includes('Festival setup is incomplete') && registerHtml.includes('registration-fest-name') && tvHtml.includes('Live display is awaiting festival setup'),
  'public view is master controlled': ['about','leaders','gallery'].every(name=>indexHtml.includes(`data-optional-link="${name}"`)&&indexHtml.includes(`publicModuleEnabled('${name}')`)) && ['results','schedule','registration','login'].every(name=>indexHtml.includes(`data-public-module="${name}"`)) && indexHtml.includes('applyOptionalSectionVisibility') && indexHtml.includes('Gallery has not been published yet.') && festConfig.includes('about: true, leaders: true, gallery: true') && festConfig.includes('login: true'),
  'public view workspace controls landing and results': adminHtml.includes('id="master-public-view-settings"') && adminMain.includes('renderPublicViewSettings') && adminMain.includes('publicViewFromDom') && festConfig.includes('DEFAULT_PUBLIC_VIEW') && festConfig.includes('showTimeline:true') && !festConfig.includes('desktopColumns:3') && indexHtml.includes("landingPlacementVisible('quickButtons'") && indexHtml.includes('landingSectionControlsPlacement') && indexHtml.includes('id="landing-quick-buttons" class="flex flex-col') && indexHtml.includes('id="landing-secondary-quick-buttons"') && indexHtml.includes(':not([data-landing-quick-item="results"])') && !indexHtml.includes('active:scale-95 mb-8') && !resultsHtml.includes('result-audience-filters') && !resultsHtml.includes('audience-nav-items') && resultsHtml.includes("xl:grid-cols-3 gap-4") && resultsHtml.includes('public-view-width') && !resultsHtml.includes('downloadItems.join') && resultsHtml.includes('resultAwards') && resultsHtml.includes('teamBreakdownValue') && resultsHtml.includes('team-breakdown-sections') && resultsHtml.includes('renderCombinedTeamRanking') && resultsHtml.includes('team-timeline-crosshair') && resultsHtml.includes('Published time') && resultsHtml.includes('team-points-table') && resultsHtml.includes('No results published yet — all teams have 0 points') && resultsHtml.includes('visibleTickCount') && resultsHtml.includes('preserveAspectRatio="xMidYMid meet"') && !resultsHtml.includes('min-w-[660px]') && !resultsHtml.includes('min-w-[620px]') && resultsHtml.includes('uniqueEvents.length<=3') && resultsHtml.includes('Published Events') && resultsHtml.includes('Total Score') && resultsHtml.includes('teamTimelineResizeTimer') && resultsHtml.includes('settings", "scoring_rules') && resultsHtml.includes('openDefaultResults') && resultsHtml.includes('defaultResultAudience') && adminMain.includes('Show Team Score Timeline') && adminMain.includes('ALL RESULTS ONLY') && adminMain.includes('Public result navigation is fixed to All') && adminMain.includes('Student, parent, default table and extra participant result tabs are removed') && !adminMain.includes('Desktop cards per row') && !adminMain.includes('Desktop width %') && !adminMain.includes('Default breakdown') && adminMain.includes('publicViewSortable') && adminMain.includes('move-public-view-item') && adminMain.includes('bindPublicViewDependencies') && adminMain.includes('Enable ${PUBLIC_VIEW_LABELS[key]||key} in Landing Sections first') && adminMain.includes('landingSectionChanged=event.target.matches') && !adminMain.includes('draggable="${locked') && adminMain.includes('data-parent-module') && festConfig.includes('LANDING_ORDER_DEFAULTS') && indexHtml.includes('applyLandingOrder') && indexHtml.includes('renderCustomLandingButtons') && adminMain.includes('CUSTOM LANDING BUTTONS') && adminMain.includes('addCustomLandingLink') && festConfig.includes('customLinks:[]'),
  'base64 image upload contract': imageUpload.includes('MAX_IMAGE_BYTES = 200 * 1024') && imageUpload.includes('readAsDataURL') && imageUpload.includes('image/jpeg') && !adminHtml.includes('Profile image URL') && !adminHtml.includes('Logo URL') && !adminHtml.includes('Gallery image URLs') && ['access-photo-file','public-home-logo-file','public-home-logo-link','public-home-gallery-file','public-home-gallery-links','public-schedule-next-bg-image-file','public-schedule-next-bg-image-links','public-tv-bg-image-file','public-tv-bg-image-link','public-tv-slides-file','public-tv-slides-links'].every(id=>adminHtml.includes(`id="${id}"`)) && adminHtml.includes('Images larger than 200 KB will be compressed automatically.') && adminHtml.includes('Each image is compressed automatically when larger than 200 KB.') && imageUpload.includes('compressImageFile') && imageUpload.includes('canvas.toBlob'),
  'optional student photos': adminHtml.includes('id="inp-std-photo-file"') && adminHtml.includes('id="edit-std-photo-file"') && adminMain.includes('photoData:document.getElementById') && adminMain.includes('studentAvatar') && firestoreRules.includes("'photoData'") && firestoreRules.includes('photoData.size() <= 280000'),
  'public schedule is master controlled': indexHtml.includes('hasPublicScheduleData') && indexHtml.includes('id="schedule" data-landing-section="schedule" class="hidden') && indexHtml.includes('data-public-module="schedule"') && indexHtml.includes("schedule:'schedule'") && !indexHtml.includes('&&hasPublicScheduleData()'),
  'direct publisher entry': publishHtml.includes('directEntryMode') && publishHtml.includes("sourceType: directEntryMode()?'direct':'judgeScore'") && publishHtml.includes('Direct Publisher Entry'),
  'open registration workflow': registerHtml.includes("httpsCallable(functions,'registrationPortal')") && adminHtml.includes('advanced-registration-status') && adminMain.includes('saveAdvancedRegistration') && firestoreRules.includes('match /registrationApplications/'),
  'final entry admin add workflow replaces participant tab': !adminHtml.includes('data-tab="participants"') && !adminHtml.includes('id="view-participants"') && ['final-entry-add-modal','final-entry-person-search','final-entry-add-body'].every(id=>adminHtml.includes(`id="${id}"`) || adminMain.includes(`id="${id}"`)) && ['open-final-entry-add','select-final-entry-person','save-final-entry-slot','delete-final-entry-member','reject-final-entry-member'].every(action=>adminMain.includes(action)) && adminMain.includes('finalEntryPeople') && adminMain.includes('teamsForExpandedEvent = expanded ? sortedTeams : registeredTeams') && adminMain.includes('entryCountLabel') && adminMain.includes("registrationSource:'admin-final-entry'") && registerHtml.includes('id="participant-id"'),
  'advanced event capabilities': ['inp-ev-participant-types','inp-ev-registration-channels','inp-ev-result-method','inp-ev-schedule-required','inp-ev-team-policy','inp-ev-score-contribution','inp-ev-scoring-policy','inp-ev-maximum-mark','edit-ev-result-method','edit-ev-scoring-policy'].every(id=>adminHtml.includes(`id="${id}"`)) && adminMain.includes('allowedParticipantTypes') && adminMain.includes('scoringOverrideForPack') && adminMain.includes('maximumMark') && firestoreRules.includes("'allowedParticipantTypes'") && firestoreRules.includes("'scoringOverride'") && firestoreRules.includes("'maximumMark'") && adminMain.includes('renderCheckboxGroup') && adminMain.includes("root.classList.add('min-w-0','w-full','max-w-full','overflow-hidden','self-start')") && adminMain.includes("input.matches?.('[data-checkbox-group]')") && adminMain.includes('renderEventEligibilityCheckboxGroups') && adminMain.includes('draftParticipantTypes') && adminMain.includes('draftRegistrationChannels') && adminMain.includes("root.dataset.checkboxDirty==='true'") && adminMain.includes("if(tab === 'events'){window.renderEventEligibilityCheckboxGroups?.()") && adminMain.includes("self:'Self Registration'") && adminMain.includes('grid min-w-0 grid-cols-1 gap-2') && adminMain.includes('data-checkbox-all') && adminMain.includes('data-schedule-stage-all') && adminMain.includes('syncScheduleStageGroups') && !adminHtml.includes('id="inp-ev-participant-types" multiple') && !adminHtml.includes('id="edit-ev-participant-types" multiple') && !adminMain.includes('Ctrl/Cmd for multiple stages'),
  'requirement-driven event form': ['master-event-field-search','master-event-field-count','master-event-field-empty'].every(id=>adminHtml.includes(`id="${id}"`)) && ['hidden','optional','required','conditional'].every(status=>adminHtml.includes(`data-event-status-filter="${status}"`)) && adminHtml.includes('data-team-limit-label="inp"') && adminHtml.includes('data-team-limit-label="edit"') && adminMain.includes('renderEventFormRequirements') && adminMain.includes('Required Event Details') && adminMain.includes('Optional Event Details') && adminMain.includes('Applicable Event Details') && adminMain.includes('data-event-hidden-storage') && adminMain.includes("'Groups Allowed per Team'") && ['event-config-panel','edit-event-config-panel','inp-ev-grpsize','edit-ev-grp'].every(id=>adminHtml.includes(`id="${id}"`)) && adminMain.includes('syncEventGroupFields') && adminMain.includes('groupInput.disabled=!groupVisible') && adminMain.includes('groupInput.required=groupVisible') && adminMain.includes(`querySelector('[data-event-requirement-section="required"] [data-event-requirement-grid]')?.append(groupWrap)`) && !adminMain.includes(`querySelector('[data-event-requirement-section="conditional"] [data-event-requirement-grid]')?.prepend(groupWrap)`),
  'single and bulk complete event model': ['inp-ev-code','inp-ev-section','inp-ev-eligible-classes','inp-ev-min-members','inp-ev-max-members','inp-ev-multiple-judge','inp-ev-tie-break','inp-ev-grade-mode','inp-ev-duration','inp-ev-preparation','inp-ev-rules'].every(id=>adminHtml.includes(`id="${id}"`)) && ['edit-ev-code','edit-ev-section','edit-ev-eligible-classes','edit-ev-min-members','edit-ev-max-members','edit-ev-multiple-judge','edit-ev-tie-break','edit-ev-grade-mode','edit-ev-duration','edit-ev-preparation','edit-ev-rules'].every(id=>adminHtml.includes(`id="${id}"`)) && adminHtml.indexOf('id="inp-ev-bulk-names"')<adminHtml.indexOf('id="inp-ev-cat"') && !adminHtml.includes('id="event-bulk-fields"') && adminMain.includes('methodFeatures') && adminMain.includes('eligibleInput') && firestoreRules.includes("'minimumMembers', 'maximumMembers'") && eventUtils.includes('Eligible class is not enabled in Master Setup'),
  'reviewed event excel import': ['event-template-modal','event-import-modal','event-import-sheet','event-import-head','event-import-body','confirm-event-import','event-criteria-modal','event-import-history','master-event-management','master-event-field-rules'].every(id=>adminHtml.includes(`id="${id}"`)) && adminHtml.includes('data-master-event-feature="excelImport"') && adminMain.includes('downloadEventTemplate') && adminMain.includes('renderEventImport') && adminMain.includes('confirmEventImport') && adminMain.includes('eventImportSessions') && adminMain.includes('downloadEventErrors') && adminMain.includes('renderEventImportHistory') && adminMain.includes('duplicateAction') && adminMain.includes('parseCriteria') && judgeJs.includes('methodInputs') && judgeJs.includes("resultMethod==='objective'") && judgeJs.includes("resultMethod==='time'") && judgeJs.includes("resultMethod==='count'") && judgeJs.includes("resultMethod==='elimination'") && firestoreRules.includes('match /eventImportSessions/'),
  'requested admin layout refinements': adminHtml.includes('id="create-event-legacy-layout"') && adminHtml.includes('id="edit-event-legacy-layout"') && !adminHtml.includes('Validation & Version Details') && adminHtml.indexOf('save-judge-assignment') < adminHtml.indexOf('judge-assignment-table') && adminHtml.includes('id="inp-new-team-logo-file"') && adminMain.includes('teamLogos') && adminHtml.includes('id="created-teams-list"') && adminHtml.includes('id="created-categories-list"'),
  'bilingual admin user guide': adminHtml.includes('data-tab="guide"') && adminHtml.includes('id="view-guide"') && adminHtml.includes('data-guide-language="en"') && adminHtml.includes('data-guide-language="ml"') && adminHtml.includes('id="guide-language-en"') && adminHtml.includes('id="guide-language-ml"') && adminHtml.includes('Basic mode') && adminHtml.includes('Advanced mode') && adminHtml.includes('ഇവിടെ നിന്ന് തുടങ്ങുക') && adminMain.includes("'set-guide-language': () => window.setGuideLanguage(d.language)") && adminMain.includes('window.setGuideLanguage') && adminMain.includes("sessionStorage.setItem('adminGuideLanguage'") && adminMain.includes("'guide': 'User Guide'"),
  'task-oriented admin navigation': ['Overview','People & Registration','Programme & Judging','Festival Configuration','Public & Display','System'].every(label=>adminHtml.includes(`>${label}</p>`)) && adminHtml.indexOf('nav-dashboard') < adminHtml.indexOf('nav-registrations') && adminHtml.indexOf('nav-registrations') < adminHtml.indexOf('nav-events') && adminHtml.indexOf('nav-events') < adminHtml.indexOf('nav-master-setup') && adminHtml.indexOf('nav-master-setup') < adminHtml.indexOf('nav-public-content') && adminHtml.indexOf('nav-public-content') < adminHtml.indexOf('nav-danger') && !adminHtml.includes('Manage Students') && !adminHtml.includes('Publishing Desk'),
  'admin application page directory': adminHtml.includes('id="admin-page-directory"') && ['admin.html','index.html','results.html','register.html','team.html','judge.html','publish.html','tv.html','login.html'].every(page=>adminHtml.includes(`data-url="${page}"`) && adminHtml.includes(`href="${page}"`)) && (adminHtml.match(/data-admin-action="copy-page-link"/g)||[]).length===9 && adminMain.includes("'copy-page-link': () => window.copyPageLink(d.url)") && adminMain.includes('navigator.clipboard.writeText(url)') && !adminHtml.slice(adminHtml.indexOf('<aside id="sidebar"'),adminHtml.indexOf('</aside>')).includes('href='),
  'template distribution adapters': resultsHtml.includes('downloadResultTemplate') && resultsHtml.includes("downloadAccess.publicResults','==',true") && teamHtml.includes('tview-certificates') && teamHtml.includes('renderTeamCertificates') && teamHtml.includes("downloadAccess.teamLeader','==',true") && firestoreRules.includes('resource.data.downloadAccess.publicResults == true') && firestoreRules.includes('resource.data.downloadAccess.teamLeader == true'),
  'unlimited ordered gallery': adminHtml.includes('Unlimited gallery images') && imageUpload.includes('data-upload-position') && !imageUpload.includes('GALLERY_SLOT_COUNT = 15') && imageUpload.includes('style="width:1.5cm;height:1.5cm"') && imageUpload.includes('slots.push(image)') && imageUpload.includes('slots.splice(Number(button.dataset.removeIndex),1)') && adminMain.includes('normalizeGallerySlots') && indexHtml.includes('Math.ceil(images.length / 3)') && indexHtml.includes('r * 3') && indexHtml.includes('gallery-lightbox-media') && indexHtml.includes('data-gallery-image') && indexHtml.includes('data-gallery-track') && indexHtml.includes('moveGalleryLightbox') && indexHtml.includes("addEventListener('touchstart'") && indexHtml.includes("addEventListener('touchend'") && indexHtml.includes("closest('.gallery-lightbox-image"),
  'basic program order': adminHtml.includes('id="basic-schedule-editor"') && adminMain.includes('renderBasicProgramOrder') && adminMain.includes('saveBasicProgramOrder') && indexHtml.includes("festSetup.scheduleMode==='basic'") && teamHtml.includes("festSetup.scheduleMode==='basic'"),
  'public group registration': registerHtml.includes('participantEligibleForEvent') && teamHtml.includes('finalizeEventApplications') && teamHtml.includes('applicationIds') && firestoreRules.includes('match /registrationApplications/'),
  'per-event team scoring and participant adapters': festConfig.includes('eventContributesToTeamScore') && [indexHtml,resultsHtml,teamHtml,tvHtml].every(source=>source.includes('eventContributesToTeamScore')) && indexHtml.includes('collection(db, "participants")') && tvHtml.includes("collection(db, 'participants')"),
  'desktop collapsible admin sidebar': adminHtml.includes('id="desktop-sidebar-toggle"') && adminHtml.includes('desktop-collapsed') && adminHtml.includes('sidebar-label') && adminHtml.includes('id="admin-sidebar-logo"') && adminHtml.includes('id="admin-sidebar-logo-fallback"') && adminMain.includes('toggleDesktopSidebar') && adminMain.includes('adminSidebarCollapsed') && adminMain.includes("document.getElementById('admin-sidebar-logo')") && adminMain.includes("matchMedia('(min-width: 768px)')") && adminMain.includes("collapsed ? 'panel-left-open' : 'panel-left-close'"),
  'access management tab': adminHtml.includes('Access Management') && adminHtml.includes('access-identifier') && adminHtml.includes('access-password') && adminHtml.includes('access-photo') && adminMain.includes('createAccessAuthUser') && adminMain.includes('saveAccessUser') && adminMain.includes('accessUsers') && adminMain.includes("doc(db, 'adminUsers'") && adminMain.includes('accessPassword: deleteField()') && !adminMain.includes('accessPassword: password'),
  'team leader gender access': adminHtml.includes('id="access-gender"') && adminMain.includes('Gender access is required for team leaders') && adminMain.includes('genderScope: role ===') && teamHtml.includes('leaderGenderScope') && teamHtml.includes('leaderCanManageStudent') && teamHtml.includes('leaderCanViewEvent') && teamHtml.includes('filter-event-gender') && teamHtml.includes('myreg-gender-filter') && teamHtml.includes('team-schedule-gender') && teamHtml.includes('report-gender-filter') && firestoreRules.includes('teamLeaderCanWriteRegistration') && firestoreRules.includes('matchesCanonicalAccessProfile'),
  'all registrations default': adminHtml.includes('<option value="all" selected>All Events</option>') && adminHtml.includes('reg-filter-participation') && adminHtml.includes('No team participated') && adminMain.includes("evId !== 'all'") && adminMain.includes('finalEntryParticipationState') && adminMain.includes('No events found for the selected filters.') && firestoreRules.includes("'cancelled'") && firestoreRules.includes("'cancelReason'"),
  'registration leader provenance': teamHtml.includes('participantMeta') && teamHtml.includes('addedByUid') && teamHtml.includes('lastUpdatedByUid') && adminMain.includes('registrationParticipantProvenance') && adminMain.includes('Added by ${escapeHtml(provenance.name)}'),
  'schedule management tab': adminHtml.includes('id="view-schedule"') && adminHtml.includes('schedule-builder-body') && adminHtml.includes('id="view-schedule-review"') && adminHtml.includes('schedule-nb-text') && adminHtml.includes('schedule-filter-status') && adminMain.includes('scheduleBreakDrafts') && adminMain.includes('selectedScheduleRows') && adminMain.includes('saveBulkSchedule') && adminMain.includes('scheduleValidation') && adminMain.includes('previewSchedulePdf'),
  'schedule builder workflow': adminHtml.includes('setup-day-label') && adminHtml.includes('setup-stage-name') && !adminHtml.includes('setup-stage-type') && !adminHtml.includes('setup-stage-start') && adminHtml.includes('setup-duration') && adminHtml.includes('auto-fill-schedule') && !adminHtml.includes('auto-suggest-schedule') && !adminHtml.includes('apply-bulk-schedule') && adminMain.includes('[5,10,20,30,60]') && adminMain.includes('dayOptionHtml') && adminMain.includes('toggleScheduleSelectAll') && adminMain.includes('indeterminate') && adminMain.includes('saveScheduleRow') && adminMain.includes('addInlineBreak') && adminMain.includes('Participant overlap'),
  'schedule review and pdf workflow': adminHtml.includes('sidebar-label">Schedule Print</span></button>') && adminHtml.includes('<h3 class="font-black">Schedule Print</h3>') && adminHtml.includes('schedule-version-select') && adminHtml.includes('schedule-column-manager') && adminHtml.includes('value="0.10"') && adminHtml.includes('value="0.25"') && !adminHtml.includes('schedule-density') && adminHtml.includes('schedule-nb-align') && adminHtml.includes('schedule-nb-pages') && !adminHtml.includes('data-export-mode="filtered"') && !adminHtml.includes('Generate PDF Preview') && !adminHtml.includes('print-schedule-preview') && adminHtml.includes('Download PDF') && adminHtml.includes('Download Excel') && adminHtml.includes('data-lucide="file-down"') && adminHtml.includes('data-lucide="sheet"') && !adminHtml.includes('Full PDF') && !adminHtml.includes('Stage PDF') && adminHtml.includes('schedule-pdf-modal') && adminHtml.includes('jspdf/2.5.1') && adminHtml.includes('jspdf-autotable') && !adminHtml.includes('mark-final-schedule') && !adminHtml.includes('unlock-schedule') && adminMain.includes('data-schedule-drag-handle') && adminMain.includes('visibleColumns') && adminMain.includes('createSchedulePdf') && adminMain.includes('notePageNumbers') && adminMain.includes('nbAlign') && adminMain.includes('nbPages') && adminMain.includes('URL.createObjectURL') && adminMain.includes('URL.revokeObjectURL') && adminMain.includes('rowPageBreak') && adminMain.includes('safeBreaks') && adminMain.includes('malayalamFontBase64') && dependencyLoader.includes('jsPDFAutoTable') && adminMain.includes('exportScheduleReviewExcel') && firestoreRules.includes('match /scheduleVersions/'),
  'schedule PDF CSP permits blob viewer': adminHtml.includes("frame-src 'self' blob:") && adminHtml.includes("object-src 'none'") && adminHtml.includes('id="schedule-pdf-frame"') && adminMain.includes('frame.src=schedulePdfUrl'),
  'schedule PDF readable typography': adminHtml.includes("font-family: 'Manjari', Arial") && adminHtml.includes('border: .65px solid') && adminHtml.includes('line-height: 1.45') && adminHtml.includes('.schedule-break-row td { background: #e2e8f0 !important; color: #0f172a !important; font-weight: 700; text-align: center; }') && adminMain.includes('safeBreaks') && adminMain.includes("fontStyle:'normal'") && adminMain.includes("lineWidth:.18") && adminMain.includes("DateTimeFormat('en-IN', { weekday: 'long' })") && adminMain.includes('scheduleBreakPrintText') && adminMain.includes(`row.type==='break'?\`<tr class="schedule-break-row"><td colspan=`),
  'registration lock in registrations': adminHtml.includes('id="view-registrations"') && adminHtml.includes('id="schedule-registration-lock"') && adminHtml.includes('save-registration-lock') && adminMain.includes('saveRegistrationLock'),
  'scoring settings tab': adminHtml.includes('Scoring Settings') && adminHtml.includes('id="master-scoring-slot"') && adminHtml.includes('id="score-policy-pack"') && adminHtml.includes('Saved together with Master Setup') && adminHtml.includes('score-enable-points') && adminHtml.includes('score-enable-grades') && adminHtml.includes('score-tie-default') && !adminHtml.includes('id="btn-save-scoring"') && adminMain.includes('SCORING_POLICY_PACKS') && adminMain.includes('MASTER_SCORING_PACK') && adminMain.includes('data-rank=') && adminMain.includes('gradeLabel') && adminMain.includes('Competition Scoring Rules'),
  'public content tab markup': adminHtml.includes('Public Page Control & Contents') && adminHtml.includes('public-home-name1') && adminHtml.includes('public-results-title') && ['home','next','results','team','social'].every(panel => adminHtml.includes(`data-public-content-panel="${panel}"`)) && adminMain.includes('switchPublicContentPanel'),
  'public content save flow': adminMain.includes('savePublicContentConfig') && adminMain.includes('settings\', \'public_config') && adminMain.includes('settings\', \'home_config'),
  'student add/edit validation': adminHtml.includes('id="form-student"') && adminHtml.includes('id="edit-student-form"') && adminMain.includes('Duplicate chest number') && adminMain.includes("updateSelect('.select-cat', '<option value=\"\">Select Category</option>' + studentCatOpts)"),
  'event add/edit/delete warning': adminHtml.includes('id="form-event"') && adminHtml.includes('id="edit-event-form"') && adminHtml.includes('id="inp-ev-bulk-names"') && adminHtml.includes('id="inp-ev-rules"') && !adminHtml.includes('id="inp-ev-notes"') && !adminHtml.includes('id="inp-ev-description"') && adminHtml.includes('id="filter-ev-gender"') && adminMain.includes('collectBulkEventNames') && adminMain.includes('buildBulkEventPayloads') && adminMain.includes('Duplicate event in bulk list') && adminMain.includes('judge assignments') && adminMain.includes('Existing linked records are not deleted automatically'),
  'desktop-safe event editor': adminHtml.includes('aria-labelledby="edit-event-title"') && adminHtml.includes('max-h-[calc(100dvh-1.5rem)]') && adminHtml.includes('overflow-y-auto overscroll-contain') && adminHtml.includes('md:grid-cols-2') && adminHtml.includes('Update Event'),
  'event and student cascade deletion': adminMain.includes('commitCascadeOperations') && adminMain.includes('PERMANENTLY DELETE ${event.name') && adminMain.includes('PERMANENTLY DELETE ${student.name') && adminMain.includes("'judgeAssignments', 'judgeScores', 'publicJudgingStatuses', 'notifications', 'auditLogs'") && adminMain.includes('participantIdsToRemove') && adminMain.includes('publishedResultId'),
  'team schedule participant drilldown': !teamHtml.includes('team-schedule-mode') && teamHtml.includes('team-schedule-category') && teamHtml.includes('openScheduleParticipants') && teamHtml.includes('schedule-participants-modal') && teamHtml.includes('All Dates') && teamHtml.includes('team-schedule-search'),
  'team scoped schedule participants': teamHtml.includes('teamScheduleParticipants') && teamHtml.includes('registration.team === currentTeam') && teamHtml.includes('leaderCanManageStudent(student)') && teamHtml.includes('from our team') && teamHtml.includes('openScheduleStudentDetails') && teamHtml.includes('window.openStudentDetails(studentId)') && teamHtml.includes('goToEventRegistration') && teamHtml.includes('if(!registrationIsLocked()) return window.openRegModal'),
  'team schedule pagination and nav icons': teamHtml.includes('id="team-schedule-page-size"') && ['30','50','80','100','130','150','200'].every(size => teamHtml.includes(`<option value="${size}"`)) && teamHtml.includes('teamSchedulePageSize = 30') && teamHtml.includes('changeTeamSchedulePage') && teamHtml.includes('team-schedule-pagination') && teamHtml.includes('Previous') && teamHtml.includes('Next') && ['layout-dashboard','calendar-days','clipboard-check','calendar-clock','file-chart-column'].every(icon => teamHtml.includes(`data-lucide="${icon}"`)) && teamHtml.includes('data-nav-label'),
  'result notification event-name search': teamHtml.includes('publishedEventName') && teamHtml.includes('events.find(event => event.id === eventId)?.name') && teamHtml.includes('results.html?search=${encodeURIComponent(publishedEventName)}') && !teamHtml.includes('results.html?search=${eventId}'),
  'public compact paginated schedule': indexHtml.includes('public-schedule-pagination') && indexHtml.includes('publicSchedulePage') && indexHtml.includes('const pageSize = 5') && indexHtml.includes('changePublicSchedulePage') && indexHtml.includes('homeConfig.logoUrl') && !indexHtml.includes('min-w-[720px]'),
  'public schedule completed-state emphasis': indexHtml.includes('publicJudgingStatuses.some') && indexHtml.includes("status==='submitted'") && indexHtml.includes("publicScheduleView = 'upcoming'") && indexHtml.includes("publicScheduleView === 'previous'") && indexHtml.includes('previousRows') && indexHtml.includes('upcomingRows') && indexHtml.includes('>Previous</span>') && indexHtml.includes('border-2 border-violet-200') && judgeJs.includes("doc(db,'publicJudgingStatuses',id)") && firestoreRules.includes('match /publicJudgingStatuses/{assignmentId}'),
  'public next-program media controls': ['public-schedule-next-text-color','public-schedule-next-bg-image','public-schedule-next-bg-video','public-schedule-next-image-interval'].every(id => adminHtml.includes(`id="${id}"`)) && adminHtml.includes('public-schedule-next-bg-image-file') && adminHtml.includes('Each image is compressed automatically when larger than 200 KB.') && adminHtml.includes('complete natural duration') && adminMain.includes('backgroundImages') && adminMain.includes('public-schedule-next-bg-image-links') && adminMain.includes('imageIntervalSeconds') && indexHtml.includes('homeConfig = {}, publicConfig = {}') && indexHtml.includes('publicConfig.nextProgramCard') && indexHtml.includes('data-next-countdown') && indexHtml.includes('nextCardRenderKey') && indexHtml.includes('IntersectionObserver') && indexHtml.includes("visibilitychange") && indexHtml.includes('autoplay muted loop playsinline') && indexHtml.includes('enablejsapi=1') && indexHtml.includes('drive.google.com/uc?export=download') && indexHtml.includes('startNextImageSlideshow') && indexHtml.includes('transition-opacity duration-700') && indexHtml.includes('^https?:\\/\\/') && indexHtml.includes('using defaults'),
  'multi-stage schedule breaks': adminMain.includes('data-schedule-stage-group') && adminMain.includes('data-schedule-stage-all') && adminMain.includes('data-schedule-stage-option') && adminMain.includes('All Stages') && !adminMain.includes('Ctrl/Cmd for multiple stages') && adminMain.includes("stageIds:row.stageIds||['__all']") && firestoreRules.includes("'stageIds', 'stages'") && indexHtml.includes('b.stages.join') && teamHtml.includes('b.stages.join'),
  'timed registration lock': adminHtml.includes('schedule-registration-lock') && adminMain.includes('registrationLockAt') && teamHtml.includes('registrationIsLocked') && teamHtml.includes('Event registrations are locked'),
  'locked entry details': teamHtml.includes('teamEntryResult') && teamHtml.includes("e.type === 'Group'") && teamHtml.includes('participant${count') && teamHtml.includes('student.chestNo'),
  'team event search and navigation': teamHtml.includes('filter-event-search') && teamHtml.includes("if(!registrationIsLocked()) return window.openRegModal") && teamHtml.includes('scrollIntoView'),
  'general participation report': teamHtml.includes('participatingGeneralStudentIds') && teamHtml.includes("leaderCanViewEvent(e) && e.category === cat") && teamHtml.includes('selfRegistrationReportRows') && teamHtml.includes("else if(e.type === 'Group') groupCount++"),
  'report PDF identity headers': teamHtml.includes("reportHeaderCell('Sl No.')") && teamHtml.includes("reportHeaderCell('Chest No.')") && teamHtml.includes("reportHeaderCell('Name','text-left')") && teamHtml.includes('report-print-bw') && !teamHtml.includes('rowspan="2" class="w-10'),
  'public page adapters': resultsHtml.includes('applyPublicConfigToUI') && teamHtml.includes('applyTeamPublicConfig'),
  'public leader cards hide total score and use team colours': !readFileSync('index.html', 'utf8').includes('Total Score: ${points} pts') && readFileSync('index.html', 'utf8').includes('teamColors[teamName]') && resultsHtml.includes('studentForResultWinner') && resultsHtml.includes('place.earnedValue ?? place.value'),
  'publishing judge sheets': publishHtml.includes('Submitted Judge Sheets for Publication') && publishHtml.includes('submittedJudgeScores') && publishHtml.includes('importJudgeScore') && publishHtml.includes('score.marks') && publishHtml.includes('enableDraggableFab') && publishHtml.indexOf('id="entry-filter-section"') < publishHtml.indexOf('id="judge-sheet-table-section"'),
  'assignment-led publishing review': publishHtml.includes('judgeAssignments = []') && publishHtml.includes('judgeSheetIssue') && publishHtml.includes('reviewableJudgeScores') && publishHtml.includes("getDoc(doc(db,'judgeAssignments'") && !publishHtml.includes('id="judge-score-source"'),
  'publisher judge sheet actions and detailed table': publishHtml.indexOf('id="judge-sheet-table-section"') < publishHtml.indexOf('id="entry-form"') && publishHtml.includes('Positions & Winners</th>') && publishHtml.includes('Grades & Winners</th>') && publishHtml.includes('Entries / Total</th>') && publishHtml.includes('judgeScoreToResult(score,event') && publishHtml.includes('processJudgeSheet') && publishHtml.includes("'published')\" class=\"rounded-lg bg-emerald") && publishHtml.includes("'ready')\" class=\"rounded-lg bg-violet") && publishHtml.includes('editJudgeSheet') && publishHtml.includes('publisherEditMode=true') && publishHtml.includes("window.switchTab('publish')") && publishHtml.includes('disabled by Admin Competition Policy'),
  'workflow-driven publishing navigation': ['dashboard','judgeSheets','publish','ready','published'].every(tab=>publishHtml.includes(`switchTab('${tab}')`)) && publishHtml.includes('judgeSheetsEnabled') && publishHtml.includes('directPublishingTabEnabled') && publishHtml.includes("festSetup.resultWorkflow !== 'judged' || canOverrideJudgeSheet()") && !publishHtml.includes('id="nav-archive"') && !publishHtml.includes('entryStatusFilter'),
  'separate direct ready and published queues': publishHtml.includes("saveResult('ready')") && publishHtml.includes("result?.status==='ready'") && publishHtml.includes("currentTab === 'ready'") && publishHtml.includes('Ready to Publish') && publishHtml.includes('renderPublishQueue') && publishHtml.includes('publishSelected()') && publishHtml.includes('Open bulk publish simulation') && publishHtml.includes('runSimulation()') && publishHtml.includes('list-filter-status') && publishHtml.includes('publishArchivedResult') && publishHtml.includes('Published / Archived Results') && publishHtml.includes('Archived. Use Publish or Edit from this list.') && publishHtml.includes('openDashboardBucket') && publishHtml.includes('id="sim-summary"') && publishHtml.includes('>Adding</th>') && publishHtml.includes('bg-red-600') && publishHtml.includes('lg:grid-cols-3') && publishHtml.includes("status==='published'?") && publishHtml.includes(':[];batch.set'),
  'ready queue selections survive filters and refreshes': publishHtml.includes('const selectedReadyResultIds = new Set()') && publishHtml.includes('window.setReadySelection') && publishHtml.includes('selectedReadyResultIds.has(r.eventId)') && publishHtml.includes('const selectedReadyIds = ()') && publishHtml.includes('pruneReadySelections()') && publishHtml.includes('const selectedIds = selectedReadyIds();'),
  'simulation PDF action avoids draggable header': !publishHtml.includes('id="sim-panel-header" class="flex shrink-0 cursor-grab') || publishHtml.includes('sm:grid-cols-3') && publishHtml.includes('> Download PDF</button>') && publishHtml.includes('onclick="downloadSimulationPdf()" class="rounded-md bg-indigo-600'),
  'simulation PDF is printable and bilingual': publishHtml.includes("await document.fonts?.ready") && !publishHtml.includes('left:-10000px') && publishHtml.includes('Programme / പരിപാടി:') && publishHtml.includes('Chest No / ചെസ്റ്റ് നമ്പർ:') && publishHtml.includes('Group / ഗ്രൂപ്പ്:') && publishHtml.includes("pagebreak:{mode:['css','legacy']}") && publishHtml.includes("format:'a4',orientation:'portrait'"),
  'publisher detailed award totals': publishHtml.includes('Judge mark: <b>') && publishHtml.includes('Position: <b>') && publishHtml.includes('Total: <b>') && publishHtml.includes("gradeLabel=gradeSelect?.value||'No Grade'") && publishHtml.includes("`${currentEvent.name||'Event'} — ${assignment?.judgeName"),
  'publisher header actions and scoring snapshot': publishHtml.includes("lg:grid-cols-[minmax(0,1fr)_190px_auto]") && publishHtml.indexOf('id="btn-archive"') < publishHtml.indexOf('id="position-sections"') && publishHtml.includes('id="scoring-snapshot-label"') && publishHtml.includes('Judge submission snapshot'),
  'admin-governed publisher override': publishHtml.includes('canOverrideJudgeSheet') && publishHtml.includes("overridePolicy()==='locked'") && publishHtml.includes('Manual override is disabled by Admin Competition Policy'),
  'publishing security and consistency': publishHtml.includes('loadPublisherProfile') && publishHtml.includes('writeBatch(db)') && publishHtml.includes('sourceVersion') && publishHtml.includes('Judge sheet changed after review') && publishHtml.includes('Admin judge assignment changed') && publishHtml.includes('result-publication') && publishHtml.includes('Mark Ready') && publishHtml.includes('Judge total:') && publishHtml.includes('Not awarded by the judge') && publishHtml.includes('snapshot?.config') && publishHtml.includes('publish-dashboard-stats') && publishHtml.includes('filter-judge') && publishHtml.includes('winner-grade-select') && publishHtml.includes('position-point-input') && publishHtml.includes('createResultRevision') && publishHtml.includes("doc(db,'teamScoreLedgers'") && firestoreRules.includes('match /resultRevisions/') && firestoreRules.includes('match /teamScoreLedgers/') && !publishHtml.includes('grade-award-sections') && !publishHtml.includes('signInAnonymously(auth)'),
  'publishing fixed-header clearance': publishHtml.includes('main.main-container, div.main-container') && publishHtml.includes('padding-top: calc(96px + env(safe-area-inset-top)) !important') && publishHtml.includes("Tailwind's p-3/md:p-6 utilities") && publishHtml.includes('@media (min-width: 768px)'),
  'published result score equation': publishHtml.includes('winnerCalculation') && publishHtml.includes('winnerLabel(winnerId, r.type)') && publishHtml.includes('positionValue ?? positionPoints') && publishHtml.includes('gradeValue ?? resultGrade?.value') && publishHtml.includes('`${points} + ${letter}(${grade}) = ${total}`') && publishHtml.includes('gradeLetter'),
  'team leaders public display': adminMain.includes('Display role is required for team leaders') && adminMain.includes("profile.role === 'teamLeader'") && adminHtml.includes('id="access-team"') && adminHtml.includes('This exact role is shown') && teamHtml.includes('team_leader_team') && indexHtml.includes('dynamicLeaders.map') && indexHtml.includes("l.title || 'Leader'"),
  'tv sections use fixed designed layouts': tvControlHtml.includes('Visibility & display order') && tvControlHtml.includes('Compact side panel beside the main result') && !tvControlHtml.includes('data-section-width') && !tvControlHtml.includes('data-section-height') && !tvControlHtml.includes('data-section-position') && tvHtml.includes('const dashboardLayouts=Object.freeze') && tvHtml.includes('leaderboard:{columns:4,compact:true}') && tvHtml.includes('media:{columns:4,compact:true}') && !tvHtml.includes('section.width') && !tvHtml.includes('section.height'),
  'tv sections use published data and strict visibility': tvHtml.includes('const publishedResults = ()') && tvHtml.includes('const recent = publishedResults()') && tvHtml.includes('const winnerDetail = (r,id)') && tvHtml.includes('if(map[team]===undefined)map[team]=0') && tvHtml.includes('videoEnabled=c.show.videos===true') && tvHtml.includes('c.control.videoUrls.length') && tvHtml.includes('const controlPlaylistLoops=') && tvHtml.includes('const advanceVideoPlaylist=') && tvHtml.includes("addEventListener('ended',advanceVideoPlaylist)") && tvHtml.includes("data?.event==='onStateChange'&&Number(data.info)===0") && tvControlHtml.includes('id="control-video-urls"') && tvControlHtml.includes("where('status','==','published')") && tvControlHtml.includes('visibleResultChecks') && tvControlHtml.includes('videoUrls=lines(\'control-video-urls\')') && tvControlHtml.includes('one URL per line') && tvControlHtml.includes('loops continuously') && tvHtml.includes('function renderAnnouncement(c,attrs=\'\')') && tvHtml.includes("length>420?'text-xl'"),
  'tv display settings tab': adminHtml.includes('data-tab="tv-display"') && tvControlHtml.includes('TV Control Room') && tvControlHtml.includes('id="config-title"') && tvControlHtml.includes('id="config-ticker"') && !tvControlHtml.includes('config-result-seconds') && tvHtml.includes("settings', 'tv_config") && tvHtml.includes('must not wait for anonymous auth'),
  'live tv result queue and media rotation': tvHtml.includes('resultQueue=[]') && tvHtml.includes('showQueuedResults') && tvHtml.includes('renderProgrammeIntro') && tvHtml.includes('renderFinalPodium') && tvHtml.includes('revealOrder') && tvHtml.includes('acceptResults') && tvHtml.includes('startSelectedControlSequence') && tvHtml.includes('rotateMedia') && tvHtml.includes("interruptPolicy==='immediate'") && tvHtml.includes('PRESENTATION_TIMING') && tvHtml.includes('programmeIntroSeconds:6') && tvHtml.includes('id="bg-youtube"') && tvHtml.includes('function youtubeEmbed') && tvHtml.includes("url.pathname==='/watch'") && tvHtml.includes("/^\\/(shorts|embed|live)\\//") && tvHtml.includes('youtube.com/embed/') && tvHtml.includes('frame-src https://www.youtube.com') && tvControlHtml.includes('id="control-video-urls"') && tvControlHtml.includes("where('status','==','published')") && tvControlHtml.includes('visibleResultChecks') && !adminMain.includes('public-tv-result-seconds') && !tvControlHtml.includes('Slide sec') && tvHtml.includes('function suspendVideos') && tvHtml.includes('videoEnabled?youtubeEmbed'),
  'judge login delegated to standalone login': !judgeHtml.includes('data-judge-action="login"') && judgeJs.includes('redirectToLogin') && judgeJs.includes('judge_access_uid'),
  'login redirect loop prevention': readFileSync('login.js', 'utf8').includes('navigateOnce') && readFileSync('login.js', 'utf8').includes('browserLocalPersistence') && judgeJs.includes('judgeAuthRedirecting') && teamHtml.includes('teamAuthRedirecting') && publishHtml.includes('publisherAuthRedirecting') && readFileSync('admin-auth.js', 'utf8').includes('adminAuthRedirecting'),
  'clean logout and cross-role routing': teamHtml.includes("window.location.replace('login.html');") && judgeJs.includes("redirectToLogin('Judge logged out. Please login again.',false)") && readFileSync('admin-auth.js', 'utf8').includes("redirectToLogin('Logged out. Please login again.', false)") && publishHtml.includes("window.location.replace('login.html');") && loginJs.includes('allowedNextPages') && loginJs.includes('clearRoleSessions'),
  'branded login and transition': loginHtml.includes('id="login-fest-name"') && loginHtml.includes('data-fest-logo') && loginHtml.includes('id="login-transition"') && !loginHtml.includes('shield-check') && !loginHtml.includes('Required: Firebase Authentication') && !loginHtml.includes('Username/email + password') && loginJs.includes('loadLoginBranding') && loginJs.includes('showLoginTransition'),
  'role username password login': loginJs.includes('resolveLoginEmail') && loginJs.includes("doc(db, 'accessUsernames', username)") && loginJs.includes('signInWithEmailAndPassword') && !loginJs.includes('signInAnonymously') && !loginJs.includes('completePasswordAccessLogin') && adminMain.includes('createUserWithEmailAndPassword') && adminMain.includes("profile.role === 'judge'") && adminMain.includes("['admin', 'superAdmin'].includes(profile.role)"),
  'judge tabbed desk': judgeHtml.includes('data-judge-action="toggle-menu"') && judgeHtml.includes('data-judge-tab="dashboard"') && judgeHtml.includes('data-judge-tab="assignments"') && judgeHtml.includes('data-judge-action="open-profile"') && judgeHtml.includes('judge-profile-modal') && !judgeHtml.includes('data-judge-tab="pending"') && judgeJs.includes('renderWorkspace') && judgeJs.includes('assignmentCard'),
  'judge compact branded UI': judgeHtml.includes('judge-fest-name') && judgeHtml.includes('judge-fest-logo') && !judgeHtml.includes('hidden md:inline-flex rounded-2xl bg-red-50') && judgeHtml.includes('data-judge-tab="drafts"') && judgeJs.includes('renderList') && judgeJs.includes('displayTime') && judgeJs.includes('statusLabel') && judgeJs.includes('participantSummary') && judgeJs.includes('Total participants') && judgeJs.includes('Total entries') && !judgeJs.includes('Continue Draft') && !judgeJs.includes('Open Scoring') && adminHtml.includes('id="judge-score-review" class="grid'),
  'admin judge review filters': adminHtml.includes('judge-review-search') && adminHtml.includes('judge-review-category') && adminHtml.includes('judge-review-stage') && adminHtml.includes('judge-review-gender') && adminMain.includes('positionOrder') && adminMain.includes('Not Published') && publishHtml.includes('openRequestedJudgeSheet'),
  'judge scoring workspace': judgeJs.includes('evaluation-input') && judgeJs.includes('score-total') && judgeJs.includes('notes-input') && judgeJs.includes('Unsaved changes') && judgeJs.includes('md:grid-cols-2') && judgeJs.includes('Evaluation<select') && judgeJs.includes('Position<select'),
  'judge draft submit': judgeJs.includes('Save Draft') && judgeJs.includes('Review & Submit') && judgeHtml.includes('Confirm Submit') && judgeJs.includes('persistScores') && !judgeJs.includes('sticky bottom-3 z-20 flex gap-2'),
  'judge workflow safety': judgeJs.includes('canLeaveWorkspace') && judgeJs.includes('setSavingState') && judgeJs.includes('validateMarks') && judgeJs.includes('participantSignature') && judgeJs.includes('This score sheet changed elsewhere') && judgeJs.includes('Save permission was denied') && judgeJs.includes('scoring service is temporarily offline') && adminMain.includes('A reopen reason is required'),
  'judge focused tabs and profile': judgeJs.includes('Total Assignments') && judgeJs.includes("statusFor(a)==='pending'") && judgeJs.includes('Reopened') && judgeJs.includes('publishLabel') && judgeJs.includes("sort((a,b)=>assignmentDate(a)-assignmentDate(b)") && !judgeJs.includes('judge-filter-stage') && !judgeJs.includes('judge-filter-gender') && judgeJs.includes('openJudgeProfile') && judgeJs.includes('judge-profile-photo') && judgeHtml.includes('width: 240px') && judgeHtml.includes('padding: 14px 20px'),
  'judge authorization and integrity': judgeJs.includes("getDoc(doc(db,'accessUsers',user.uid))") && judgeJs.includes('id:user.uid,uid:user.uid,authUid:user.uid') && !judgeJs.includes("collection(db,'judges')") && !loginJs.includes("sessionStorage.setItem('judge_user'") && judgeJs.includes('runTransaction') && judgeJs.includes('memberIds') && judgeJs.includes('Duplicate participant registrations') && judgeJs.includes('Review every entry before submitting') && judgeJs.includes("error?.code==='permission-denied'") && firestoreRules.includes('judgeOwnsAssignment') && firestoreRules.includes('judgeId == request.auth.uid') && firestoreRules.includes("!('active' in get(assignmentDoc(assignmentId)).data)") && firestoreRules.includes("resource.data.status == 'draft'") && firestoreRules.includes('request.resource.data.assignmentId == resource.data.assignmentId'),
  'judge coordinated scoped data': judgeJs.includes('requiredSources') && judgeJs.includes('dataReady') && judgeJs.includes('bindAssignmentScope') && judgeJs.includes("where(documentId(),'in',idsChunk)") && judgeJs.includes("where('eventId','in',idsChunk)") && judgeJs.includes('loadState[name]=\'error\''),
  'judge accessible dialogs': judgeHtml.includes('aria-labelledby="judge-submit-title"') && judgeHtml.includes('aria-labelledby="judge-profile-name"') && judgeJs.includes("event.key==='Escape'") && judgeJs.includes("event.key!=='Tab'") && judgeJs.includes('lastFocusedElement') && judgeJs.includes('photo.onerror'),
  'role profile identity cards': judgeHtml.includes('id="judge-profile-logo"') && judgeHtml.includes('h-20 w-20') && judgeJs.includes("currentJudge.username||'—'") && judgeJs.includes("['judge-fest-logo','judge-profile-logo']") && teamHtml.includes('id="team-profile-modal"') && teamHtml.includes('openTeamProfile()') && teamHtml.includes('team-profile-logo') && teamHtml.includes('team-profile-gender') && teamHtml.includes('currentLeaderProfile.photoUrl'),
  'judge scoped loading and errors': judgeHtml.includes('judge-page-state') && judgeJs.includes("where('judgeId','in',ids.slice(0,30))") && judgeJs.includes('Unable to load ${name}') && judgeJs.includes('sticky top-24') && judgeJs.includes('judge-save-state'),
  'complete specific reset controls': adminHtml.includes('id="specific-reset-grid"') && adminMain.includes('RESET_SCOPES') && ['participants','registrationRequests','scheduleVersions','judgeScores','settings','auditLogs','deletedBackups'].every(name=>adminMain.includes(`'${name}'`)) && adminMain.includes('clearEventScheduleFields') && adminMain.includes('clearNonAdminAccess'),
  'protected factory reset': adminHtml.includes('Delete Everything Except Admin Login') && adminHtml.includes('id="reset-progress"') && adminHtml.includes('id="reset-progress-bar"') && adminHtml.includes('id="reset-progress-percent"') && adminMain.includes('FACTORY_RESET_COLLECTIONS') && adminMain.includes('posterCertificateSources') && adminMain.includes("completeFactoryReset({confirmation:'DELETE EVERYTHING'})") && resetFunction.includes("PROTECTED_COLLECTIONS = new Set(['adminUsers', 'adminUsernames'])") && resetFunction.includes('db.listCollections()') && resetFunction.includes('db.recursiveDelete') && resetFunction.includes("ADMIN_ROLES.has(item.data().role)"),
  'dependency-safe team reset': adminHtml.includes("participants, requests, applications, registrations, policies, notifications and non-admin leader access") && ['participants','registrationRequests','registrationApplications','teamRegistrationPolicies','teamLeaders','accessUsers','accessUsernames'].every(name=>adminMain.includes(`collection(db,\"${name}\")`)),
  'poster certificate placeholder': adminHtml.includes('data-tab="poster-certificate"') && adminHtml.includes('id="view-poster-certificate"') && adminHtml.includes('Updating very soon') && !adminHtml.includes('id="pc-template-library"') && !adminMain.includes('initPosterCertificateAdmin'),
  'advanced student registration portal': ['verifyRegistrationIdentity','registrationPortal','searchRegistrationCandidates'].every(marker=>readFileSync('functions/index.js','utf8').includes(marker)) && ['identity-form','name-suggestions','verify-dialog','eligible-events','my-applications','application-note'].every(id=>registerHtml.includes(`id="${id}"`)) && ['verification-loader','verification-loader-logo','verification-loader-title','verify-submit','verify-toggle-chest'].every(id=>registerHtml.includes(`id="${id}"`)) && registerHtml.includes('Chest number is incorrect.') && registerHtml.includes('Enter the chest number given by the administrator.') && !registerHtml.includes('one or more digits and uppercase/lowercase') && ['registration-window-banner','registration-window-title','registration-window-text'].every(id=>registerHtml.includes(`id="${id}"`)) && registerHtml.includes("onSnapshot(doc(db,'settings','registration_config')") && registerHtml.includes('type="password" inputmode="text" autocomplete="new-password"') && registerHtml.includes('Verify &amp; Login') && registerHtml.includes('verifyStudentLegacy') && readFileSync('functions/index.js','utf8').includes('chestCode(student.chestNo)') && registerHtml.includes('Initializing…') && registerHtml.includes('Verifying…') && registerHtml.includes('Updating…') && adminHtml.includes('advanced-registration-status') && teamHtml.includes('team-applications-list') && firestoreRules.includes('match /registrationApplications/{applicationId}'),
  'registration database-backed portal': registerHtml.includes('staticDbStudentVerification') && registerHtml.includes("collection(db,'registrationRequests')") && !registerHtml.includes('localRegistrationApplications') && registerHtml.includes('staticDbPortalData') && registerHtml.includes('normalizeApplicationRows') && registerHtml.includes('statusInfo') && firestoreRules.includes('match /registrationRequests/{requestId}') && firestoreRules.includes('allow read: if true;'),
  'registration management workspaces': registerHtml.includes('data-view="dashboard"') && registerHtml.includes('xl:grid-cols-3') && adminHtml.includes('advanced-limit-total-enabled') && adminHtml.includes('application-filter-category') && adminHtml.includes('admin-application-detail-dialog') && adminMain.includes('<table class="min-w-[1250px]') && teamHtml.includes('tview-selfreg') && teamHtml.includes('Self Registration Applications') && teamHtml.includes('decideUnifiedApplication'),
  'team event information dialog': ['team-event-info-dialog','team-event-info-title','team-event-info-body'].every(id=>teamHtml.includes(`id="${id}"`)) && teamHtml.includes('openTeamEventInfo') && teamHtml.includes('Judging Criteria') && !teamHtml.includes('leading-relaxed mt-2 bg-slate-50 border border-slate-100 rounded-xl p-3'),
  'student participation downloads report': adminHtml.includes('data-tab="downloads"') && adminHtml.includes('id="view-downloads"') && ['student-report-group-full-points','student-report-category','student-report-class','student-report-gender','student-report-team','student-report-result-status','student-report-group-by','student-report-sort-by','student-report-page-break','student-report-orientation','student-report-rank-filter','student-report-participation-filter','student-report-columns','student-report-pdf-modal'].every(id=>adminHtml.includes(`id="${id}"`)) && adminHtml.includes('Review PDF') && adminHtml.includes('Not participated only') && adminMain.includes("['sl','SL']") && adminMain.includes('student-report-participation-filter') && adminMain.includes('sr-col-chest') && !adminHtml.includes('reset-student-participation-report') && !adminHtml.includes('bg-blue-600 px-5 py-3 text-xs font-black text-white">Download PDF') && ['STUDENT_REPORT_COLUMNS','selectedStudentReportColumns','studentParticipationReportRows','studentParticipationEventDetails','resultAwardsForReport','normalizeReportPosition','groupStudentReportRows','sortStudentReportRows','createStudentParticipationReportPdf','exportStudentParticipationReportExcel'].every(marker=>adminMain.includes(marker)),
  'registration download centre': adminHtml.includes('data-registration-admin-tab="downloads"') && ['registration-export-class','registration-export-team','registration-export-category','registration-export-gender','registration-export-order','registration-export-from','registration-export-to','registration-export-model','registration-pdf-modal'].every(id=>adminHtml.includes(`id="${id}"`)) && ['createRegistrationTablePdf','createRegistrationStudentPdf','exportRegistrationExcel','jsPDF 2.5.1','AutoTable 3.8.4'].every(marker=>adminMain.includes(marker)),
  'registration application media policy': ['application-images','application-image-preview','apply-event-details','application-view-dialog','participation-limit-dialog'].every(id=>registerHtml.includes(`id="${id}"`)) && registerHtml.includes('compressApplicationImage') && registerHtml.includes('300*1024') && resetFunction.includes('Maximum 1 image is allowed.') && resetFunction.includes("Buffer.from(match[2], 'base64')") && ['advanced-field-description','advanced-field-youtube','advanced-field-reference','advanced-field-images','advanced-application-update-missing','advanced-application-update-replace','advanced-show-rules','advanced-show-criteria','advanced-limit-total-mode'].every(id=>adminHtml.includes(`id="${id}"`)) && registerHtml.includes('openApplicationUpdate') && registerHtml.includes('updateApplicationMedia') && resetFunction.includes('mediaUpdatePayload') && firestoreRules.includes('allowApplicationMediaAddMissing'),
  'registration participant selection safety': adminMain.includes('At least one participant type is required. Enable another type before disabling this one.') && adminMain.includes("selectedParticipantTypes=checkedValues('master-participants')") && adminMain.includes('To disable Student, enable another type first.') && adminMain.includes('const normalizeChestCode=') && adminHtml.includes('maxlength="32" autocomplete="off" autocapitalize="off" id="edit-std-chest"') && firestoreRules.includes('request.resource.data.chestNo is string'),
  'registration overload and team policy': readFileSync('registration-utils.js','utf8').includes("state: count > capacity ? 'overloaded'") && teamHtml.includes('OVERLOADED') && teamHtml.includes('finalizeEventApplications') && firestoreRules.includes('match /teamRegistrationPolicies/{teamId}'),
};

let failed = false;
for (const [name, ok] of Object.entries(checks)) {
  console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`);
  failed ||= !ok;
}
if (failed) throw new Error('Static smoke check failed');
console.log('Static smoke coverage check passed');
